version: '3.7'
services:
  mongo:
      container_name: mongo
      image: mongo
      volumes:
        - ./mongo-volume:/data/db             
      restart: always
      ports:
        - "27017:27017"
  redis:
      container_name: redis
      image: redis
      volumes:
        - ./redis-volume:/data   
      ports:
        - "6379:6379"          
      restart: always    
  screeps:
      container_name: screeps
      image: ffmathy/screeps-server
      ports:
        - "21025:21025"
      environment:
        - STEAMKEY=
        - MONGO_LINK=mongo
        - REDIS_LINK=redis
      volumes:
        - ./screeps-volume:/app
      depends_on:
        - mongo
        - redis
      restart: always

volumes:
    mongo-volume:
      driver: local
    redis-volume:
      driver: local
    screeps-volume:
      driver: local