version: '3.7'
services:
  screeps-mongo:
      container_name: screeps-mongo
      image: mongo
      volumes:
        - mongo-volume:/data/db             
      restart: always
  screeps-redis:
      container_name: screeps-redis
      image: redis
      volumes:
        - redis-volume:/data            
      restart: always    
  screeps-server:
      container_name: screeps-server
      image: ffmathy/screeps-server
      ports:
        - "21025:21025"
      environment:
        - STEAMKEY=
        - MONGO_LINK=screeps-mongo
        - REDIS_LINK=screeps-redis
      volumes:
        - ./screeps-volume:/app
      depends_on:
        - screeps-mongo
        - screeps-redis
      restart: always

volumes:
    mongo-volume:
      driver: local
    redis-volume:
      driver: local
